name = "api-land-random-script"
type = "javascript"
zone_id = ""
account_id = "d67db13a3ebe7fdd8f769b823c9643f9"
route = ""
workers_dev = true
compatibility_date = "2022-02-07"

[build]
command = "yarn install && yarn run build"
[build.upload]
format = "service-worker"


[vars]
API_URL="https://jsonblob.com/api/uha40/scripts"
BLOB_ID="940319907325952000"
